config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders, only: [:index, :new, :create]
  resources :plain_waffles, only: :index
  resources :choco_waffles, only: :index
  resources :matcha_waffles, only: :index
  resources :lemon_waffles, only: :index
  resources :maple_waffles, only: :index
  resources :users, only: :show
  root "orders#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :signup_at, presence: true
  validates :time, presence: true
  validates :WaffleSelect, presence: true
  validate :date_cannot_be_in_the_past
  belongs_to :user
  
  private
    def WaffleSelect
      plain.presence or choco.presence or matcha.presence or lemon.presence or maple.presence
    end
    def date_cannot_be_in_the_past
      if signup_at.present? && signup_at < Date.today
        errors.add(:signup_at, ": 過去の日付は使用できません")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true
  has_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/choco_waffles_controller.rb
class ChocoWafflesController < ApplicationController
  def index
  end
end

app/controllers/lemon_waffles_controller.rb
class LemonWafflesController < ApplicationController
  def index
  end
end

app/controllers/maple_waffles_controller.rb
class MapleWafflesController < ApplicationController
  def index
  end
end

app/controllers/matcha_waffles_controller.rb
class MatchaWafflesController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :move_to_index, except: :index

  def index
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
    else
      render :new
    end
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def order_params
    params.require(:order).permit(:plain, :choco, :matcha, :lemon, :maple, :signup_at, :time, :total).merge(user_id: current_user.id)
  end
end

app/controllers/plain_waffles_controller.rb
class PlainWafflesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name 
    @orders = current_user.orders
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/choco_waffles/index.html.haml
.information
  .explanation
    .explanation__image
      = image_tag "/choco.jpg", alt: "チョコ", id: "camera"
    .explanation__waffle
      %h1.explanation__waffle--code
        チョコワッフル
      .explanation__waffle--info
        ビタースウィートチョコをコーティングしました
      .explanation__waffle--price
        150円（税抜き)
  .bottom
    .detail
      .detail__allergies
        アレルギー情報
      .detail__contents
        特定原材料７品目
      %table
        %tr.allergies_area
          %th
            卵
          %th 
            乳
          %th 
            小麦
          %th 
            落花生
          %th 
            そば
          %th 
            えび
          %th 
            かに
        %tr
          %td
            ●
          %td 
            ●
          %td 
            ●
          %td 
            ×
          %td 
            ×
          %td 
            ×
          %td  
            ×
      .detail__nutritional
        栄養成分情報(１個あたり)
      .detail__contents
        %table
          %tr.nutritional_area
            %th
              エネルギー kcal
            %th 
              たんぱく質 g
            %th 
              脂質 g
            %th 
              炭水化物 g
            %th 
              食塩相当量 g
          %tr
            %td
              267
            %td 
              4.2
            %td 
              15
            %td 
              28.8
            %td 
              0.2
  .change
    .chage__box
      = link_to "メニューに戻る", :back

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WaffleReserve
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    .Header
      .Header__logo
        = link_to orders_path do
          waffle_reserve
      .Header__info
        - if user_signed_in?
          .Header__info--user
            .user_name
              = link_to "/users/#{current_user.id}" do
                = icon('fas', 'user')
                = current_user.name
            .user_out
              = link_to  destroy_user_session_path, method: :delete do
                = icon('fas', 'sign-out-alt')
                ログアウト
        - else
          .Header__info--user
            .user_name
              = link_to new_user_session_path do
                = icon('fas', 'sign-in-alt')
                ログイン
            .user_out
              = link_to new_user_registration_path do
                = icon('fas', 'user-plus')
                新規登録
    = yield

app/views/lemon_waffles/index.html.haml
.information
  .explanation
    .explanation__image
      = image_tag "/remon&tea.jpg", alt: "檸檬と紅茶", id: "camera"
    .explanation__waffle
      %h1.explanation__waffle--code
        檸檬紅茶ワッフル
      .explanation__waffle--info
        レモンピールとダージリンの茶葉を練り込んだワッフルです
      .explanation__waffle--price
        150円（税抜き)
  .bottom
    .detail
      .detail__allergies
        アレルギー情報
      .detail__contents
        特定原材料７品目
      %table
        %tr.allergies_area
          %th
            卵
          %th 
            乳
          %th 
            小麦
          %th 
            落花生
          %th 
            そば
          %th 
            えび
          %th 
            かに
        %tr
          %td
            ●
          %td 
            ●
          %td 
            ●
          %td 
            ×
          %td 
            ×
          %td 
            ×
          %td  
            ×
      .detail__nutritional
        栄養成分情報(１個あたり)
      .detail__contents
        %table
          %tr.nutritional_area
            %th
              エネルギー kcal
            %th 
              たんぱく質 g
            %th 
              脂質 g
            %th 
              炭水化物 g
            %th 
              食塩相当量 g
          %tr
            %td
              220
            %td 
              3.8
            %td 
              11.8
            %td 
              24.6
            %td 
              0.2
  .change
    .chage__box
      = link_to "メニューに戻る", :back

app/views/maple_waffles/index.html.haml
.information
  .explanation
    .explanation__image
      = image_tag "/maple.jpg", alt: "メープル", id: "camera"
    .explanation__waffle
      %h1.explanation__waffle--code
        メープルワッフル
      .explanation__waffle--info
        メープルシロップを使用したコクのある味わいのワッフルです
      .explanation__waffle--price
        150円（税抜き)
  .bottom
    .detail
      .detail__allergies
        アレルギー情報
      .detail__contents
        特定原材料７品目
      %table
        %tr.allergies_area
          %th
            卵
          %th 
            乳
          %th 
            小麦
          %th 
            落花生
          %th 
            そば
          %th 
            えび
          %th 
            かに
        %tr
          %td
            ●
          %td 
            ●
          %td 
            ●
          %td 
            ×
          %td 
            ×
          %td 
            ×
          %td  
            ×
      .detail__nutritional
        栄養成分情報(１個あたり)
      .detail__contents
        %table
          %tr.nutritional_area
            %th
              エネルギー kcal
            %th 
              たんぱく質 g
            %th 
              脂質 g
            %th 
              炭水化物 g
            %th 
              食塩相当量 g
          %tr
            %td
              222
            %td 
              3.9
            %td 
              11.7
            %td 
              25.1
            %td 
              0.2
  .change
    .chage__box
      = link_to "メニューに戻る", :back

app/views/matcha_waffles/index.html.haml
.information
  .explanation
    .explanation__image
      = image_tag "/matcha.jpg", alt: "宇治抹茶", id: "camera"
    .explanation__waffle
      %h1.explanation__waffle--code
        宇治抹茶ワッフル
      .explanation__waffle--info
        京都産宇治抹茶と北海道小豆を練り込んだワッフルです
      .explanation__waffle--price
        150円（税抜き)
  .bottom
    .detail
      .detail__allergies
        アレルギー情報
      .detail__contents
        特定原材料７品目
      %table
        %tr.allergies_area
          %th
            卵
          %th 
            乳
          %th 
            小麦
          %th 
            落花生
          %th 
            そば
          %th 
            えび
          %th 
            かに
        %tr
          %td
            ●
          %td 
            ●
          %td 
            ●
          %td 
            ×
          %td 
            ×
          %td 
            ×
          %td  
            ×
      .detail__nutritional
        栄養成分情報(１個あたり)
      .detail__contents
        %table
          %tr.nutritional_area
            %th
              エネルギー kcal
            %th 
              たんぱく質 g
            %th 
              脂質 g
            %th 
              炭水化物 g
            %th 
              食塩相当量 g
          %tr
            %td
              231
            %td 
              4.1
            %td 
              12.1
            %td 
              26.5
            %td 
              0.1
  .change
    .chage__box
      = link_to "メニューに戻る", :back

app/views/orders/create.html.haml
.Finish
  .Finish__contents
    ご注文が完了しました
  .Finish__contents
    ご来店お待ちしております
  .Finish__reserve
    .Finish__reserve--select
      ご注文内容
    .Finish__reserve--plain
      - if @order.plain.present?
        %p.plain
          プレーン
          = @order.plain
          個
    .Finish__reserve--choco
      - if @order.choco.present?
        %p.choco
          チョコ
          = @order.choco
          個
    .Finish__reserve--matcha
      - if @order.matcha.present?
        %p.matcha
          宇治抹茶
          = @order.matcha
          個
    .Finish__reserve--lemon
      - if @order.lemon.present?
        %p.lemon
          檸檬と紅茶
          = @order.lemon
          個
    .Finish__reserve--maple
      - if @order.maple.present?
        %p.maple
          メープル
          = @order.maple
          個
    .Finish__reserve--total
      合計金額(税込み)
      = @order.total
      円
    .Finish__reserve--day
      ご予約日
      = @order.signup_at.strftime("%Y年%m月%d日")
    .Finish__reserrve--hour
      お受け取り時間
      = @order.time.strftime("%H時%M分") 
  .Finish__link
    = link_to "トップページに戻る", '/orders'

app/views/orders/index.html.haml
.Wrapper
  .Contents
    = link_to lemon_waffles_path do
      = image_tag "/waffleB.jpg", alt: "トップ画面", class: "Contents__image"
  .Select
    %h1.Select__waffle
      menu
    %p.Select__waffleB
  .Waffles
    .Waffles__box
      = link_to plain_waffles_path do
        = image_tag "/plain.jpg", alt: "プレーン", id: "camera", class: "Waffles__box--image"
        .Waffles__box--title
          プレーンワッフル
        .Waffles__box--text
          蜂蜜とバターの風味豊かなワッフルです
        .Waffles__box--price
          150円（税込み)    
    .Waffles__box
      = link_to choco_waffles_path do
        = image_tag "/choco.jpg", alt: "チョコ", id: "camera",class: "Waffles__box--image"
        .Waffles__box--title
          チョコワッフル
        .Waffles__box--text
          ビタースウィートチョコをコーティングしました
        .Waffles__box--price
          150円（税込み）
    .Waffles__box
      = link_to matcha_waffles_path do
        = image_tag "/matcha.jpg", alt: "宇治抹茶", id: "camera", class: "Waffles__box--image"
        .Waffles__box--title
          宇治抹茶ワッフル
        .Waffles__box--text
          京都産宇治抹茶と北海道小豆を練り込んだワッフルです
        .Waffles__box--price
          150円（税込み）
    .Waffles__box 
      = link_to lemon_waffles_path do
        = image_tag "/remon&tea.jpg", alt: "檸檬と紅茶", id: "camera", class: "Waffles__box--image"
        .Waffles__box--title
          檸檬紅茶ワッフル
        .Waffles__box--text
          レモンピールとダージリンの茶葉を練り込んだワッフルです
        .Waffles__box--price
          150円（税込み）
    .Waffles__box
      = link_to maple_waffles_path do
        = image_tag "/maple.jpg", alt: "メープル", id: "camera", class: "Waffles__box--image"
        .Waffles__box--title
          メープルワッフル
        .Waffles__box--text
          メープルシロップを使用したコクのある味わいのワッフルです
        .Waffles__box--price
          150円（税込み）
  .Form
    = link_to "注文画面に進む", "/orders/new", class:"Form__contents"

  

app/views/orders/new.html.haml
.Wrapper_new  
  .Title
    .Title__first
      ご注文内容を入力してください
  .FormSelect
    = form_with model: @order, id:"form", local: true do |f| 
      - if @order.errors.any?
        .FormSelect__errors
          %h2= "#{@order.errors.full_messages.count}件のエラーが発生しました。"
          %ul
            - @order.errors.full_messages.each do |message|
              %li= message  
      .Selects
        .Selects__waffle
          プレーンワッフル(個)
          = f.number_field :plain, class:"Selects__waffle--fleaver", min: 1
        .Selects__waffle
          チョコワッフル(個)
          = f.number_field :choco, class:"Selects__waffle--fleaver", min: 1
        .Selects__waffle
          宇治抹茶ワッフル(個)
          = f.number_field :matcha, class:"Selects__waffle--fleaver", min: 1
        .Selects__waffle
          檸檬紅茶ワッフル(個)
          = f.number_field :lemon, class:"Selects__waffle--fleaver", min: 1
        .Selects__waffle
          メープルワッフル(個)
          = f.number_field :maple, class:"Selects__waffle--fleaver", min: 1
          合計金額（税込み）
          .Selects__waffle--box
            = f.text_field :total, readonly: true, class:"Selects__waffle--total"
            円
          .Selects__waffle--space
          ご予約日
          = f.date_field :signup_at
          お受け取り時間
        .Selects__hour   
          = f.time_field :time, { min: "11:00:00", max: "20:00:00" }
        = f.submit "注文を確定する", class:"Send_btn"
        
        .Back
          = link_to "メニューに戻る", :back

app/views/plain_waffles/index.html.haml
.information
  .explanation
    .explanation__image
      = image_tag "/plain.jpg", alt: "プレーン", id: "camera" 
    .explanation__waffle
      %h1.explanation__waffle--code
        プレーンワッフル
      .explanation__waffle--info
        蜂蜜とバターの風味豊かなワッフルです
      .explanation__waffle--price
        150円（税抜き)
  .bottom
    .detail
      .detail__allergies
        アレルギー情報
      .detail__contents
        特定原材料７品目
      %table
        %tr.allergies_area
          %th
            卵
          %th 
            乳
          %th 
            小麦
          %th 
            落花生
          %th 
            そば
          %th 
            えび
          %th 
            かに
        %tr
          %td
            ●
          %td 
            ●
          %td 
            ●
          %td 
            ×
          %td 
            ×
          %td 
            ×
          %td  
            ×
      .detail__nutritional
        栄養成分情報(１個あたり)
      .detail__contents
        %table
          %tr.nutritional_area
            %th
              エネルギー kcal
            %th 
              たんぱく質 g
            %th 
              脂質 g
            %th 
              炭水化物 g
            %th 
              食塩相当量 g
          %tr
            %td
              220
            %td 
              3.8
            %td 
              11.8
            %td 
              24.6
            %td 
              0.2
  .change
    .chage__box
      = link_to "メニューに戻る", :back

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", '#', class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'

app/views/users/show.html.haml
.wall
  .history
    .history__box
      = "#{@name}さんの注文一覧"
  .order_list
    - @orders.each do |order|
      .order_list__contents
        .order_list__contents--box
          ご注文内容
        .plain
          - if order.plain.present?
            %p.plain
              プレーン
              = order.plain
              個
        .choco
          - if order.choco.present?
            %p.choco
              チョコ
              = order.choco
              個
        .matcha
          - if order.matcha.present?
            %p.matcha
              宇治抹茶
              = order.matcha
              個
        .lemon
          - if order.lemon.present?
            %p.lemon
              檸檬と紅茶
              = order.lemon
              個
        .maple
          - if order.maple.present?
            %p.maple
              メープル
              = order.maple
              個
        .total
          合計金額(税込み)
          = order.total
          円
        .day
          ご予約日
          = order.signup_at.strftime("%Y年%m月%d日")
        .hour
          お受け取り時間
          = order.time.strftime("%H時%M分")
  .return
    .return__box
      = link_to "メニューに戻る", :back